on:
  push:
    branches: [main]
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          remote_path: '/home/ubuntu/DocsWebFlowConecta'
          ssh_private_key: ${{ secrets.SFTP_SECRET_KEY }}
          sftp_only: true

      - name: Install Dependencies and Build on Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} 'cd /caminho/do/seu/projeto && npm i && npm run prod'
