on:
  push:
    branches: [main]
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          remote_path: '/usr/share/nginx/html/public/DocsWebFlowConecta'
          ssh_private_key: ${{ secrets.SFTP_SECRET_KEY }}
          delete_remote_files: true
          sftp_only: false
          
      - name: Install dependencies and build the project
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.SFTP_SECRET_KEY }}
          port: ${{ secrets.FTP_PORT }}
          script: | 
            cd /usr/share/nginx/html/public/DocsWebFlowConecta
            sudo npm i
            sudo npm run prod
